# Generated by Django 5.2.12 on 2026-03-09 14:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('email_verified', models.BooleanField(default=False)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('warning', 'Warning'), ('blocked', 'Blocked')], default='allowed', max_length=20)),
                ('is_developer', models.BooleanField(default=False)),
                ('total_earning', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['is_developer'], name='users_is_deve_428dbf_idx')],
            },
        ),
    ]
