# Generated by Django 5.2.12 on 2026-03-09 14:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('developer_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='agents.agent')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to='users.user')),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_transactions', to='users.user')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id'], name='transaction_agent_i_eb1885_idx'), models.Index(fields=['developer_id'], name='transaction_develop_2729f9_idx'), models.Index(fields=['client_id'], name='transaction_client__90b104_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx')],
            },
        ),
    ]
