# Generated by Django 5.2.12 on 2026-03-09 14:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_fees', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('agent_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('subscription_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('rating', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8')), django.core.validators.MaxValueValidator(Decimal('5.00000000'))])),
                ('subscription_duration_days', models.IntegerField(default=30)),
                ('agent_template', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agents', to='users.user')),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['developer_id'], name='agents_develop_fe4e8c_idx'), models.Index(fields=['status'], name='agents_status_f5ff61_idx'), models.Index(fields=['created_at'], name='agents_created_697d3a_idx')],
            },
        ),
    ]
