# Generated by Django 5.2.12 on 2026-03-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('capability_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'capabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityMapper',
            fields=[
                ('capability_mapper_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities_rel', to='agents.agent')),
                ('capability_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents_rel', to='agents.capability')),
            ],
            options={
                'db_table': 'cap_mapper',
                'ordering': ['created_at'],
                'unique_together': {('agent_id', 'capability_id')},
            },
        ),
    ]
