# Generated by Django 5.2.12 on 2026-03-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_capability_capabilitymapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='output_template',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
