# Generated by Django 5.2.12 on 2026-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_output_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
    ]
